version: 2
jobs:

  build:
    docker:
      - image: verypossible/serverless:1.25.0-python3
      - image: postgres
    environment:
      - ENV: circleci
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "ch2/requirements.txt" }}
      - run:
          name: Install python requirements
          working_directory: ch2
          command: make libs
      - save_cache:
          key: dependency-cache-{{ checksum "ch2/requirements.txt" }}
          paths:
            - ch2/lib
      - run:
          name: py.test
          working_directory: ch2
          command: make tests
      - store_artifacts:
          path: ch2/htmlcov/
          destination: coverage

  deploy:
    docker:
      - image: verypossible/serverless:1.25.0-python3
    environment:
      - ENV: production
      - AWS_REGION: us-west-2
      - VPC_ID: vpc-b7d759d1
      - SUBNET_ID_A: subnet-4a254c11
      - SUBNET_ID_B: subnet-76b16810
      - SUBNET_ID_C: subnet-bda25ff5
      - CUPPING_DB_USERNAME: root
      - CUPPING_DB_NAME: cupping_log
    steps:
      - checkout
      - run:
          name: Build libs
          working_directory: ch2
          command: make libs
      - run:
          name: Production deploy if tests pass and branch is Master
          working_directory: ch2
          command: make deploy


workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: production
