service: gdax-lambda-arch

provider:
  name: aws
  runtime: python3.6
  stage: ${env:ENV}
  region: ${env:AWS_REGION}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::brianz-gdax-${env:ENV}-firehose"
        - "arn:aws:s3:::brianz-gdax-${env:ENV}-firehose/*"

package:
  exclude:
    - .git/**
    - __pycache__/**
    - "**/__pycache__/**"
    - "*.pyc"
    - "*.swp"


resources:
  Resources:
    GdaxFirehoseStream:
      Type: AWS::KinesisFirehose::DeliveryStream
      Properties:
        DeliveryStreamName: brianz-gdax-${env:ENV}-stream
        DeliveryStreamType: DirectPut
        S3DestinationConfiguration:
          BucketARN: "arn:aws:s3:::brianz-gdax-${env:ENV}-firehose"
          BufferingHints:
            IntervalInSeconds: 60
            SizeInMBs: 5
          CompressionFormat: UNCOMPRESSED
          RoleARN: "arn:aws:iam::679892560156:role/brianz_firehose_delivery_role"

functions:
  hello:
    handler: handler.hello
    events:
      - s3:
          bucket: brianz-gdax-${env:ENV}-firehose
          event: s3:ObjectCreated:*

# you can add CloudFormation resource templates here
#resources:
#  Resources:
#    NewResource:
#      Type: AWS::S3::Bucket
#      Properties:
#        BucketName: my-new-bucket
#  Outputs:
#     NewOutput:
#       Description: "Description for the output"
#       Value: "Some output value"
