service: map-reduce

provider:
  name: aws
  runtime: python3.6
  memorySize: 1024
  timeout: 300
  region: ${env:AWS_REGION}
  environment:
    MAPREDUCE_SNS_ARN:
      Ref: SNSMapperTopic
    REDUCE_RESULTS_BUCKET: "brianz-${env:ENV}-mapreduce-results"
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::big-data-benchmark"
        - "arn:aws:s3:::big-data-benchmark/*"
        - "arn:aws:s3:::brianz-mapreduce-enron-emails"
        - "arn:aws:s3:::brianz-mapreduce-enron-emails/*"
        - "arn:aws:s3:::brianz-${env:ENV}-mapreduce-results"
        - "arn:aws:s3:::brianz-${env:ENV}-mapreduce-results/*"
    - Effect: "Allow"
      Action:
        - "sns:*"
      Resource:
        Ref: SNSMapperTopic
    # - Effect: Allow
    #   Action:
    #     - lambda:InvokeFunction
    #   Resource:
    #     - "arn:aws:lambda:${env:AWS_REGION}:*:function:map-reduce-${opt:stage}-Reducer"
    #     - "arn:aws:lambda:${env:AWS_REGION}:*:function:map-reduce-${opt:stage}-FinalReducer"

package:
  exclude:
    - .git/**
    - __pycache__/**
    - "**/__pycache__/**"
    - "*.pyc"
    - "*.swp"

resources:
  Resources:
    SNSMapperTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: ${env:ENV} notification for mappers
        TopicName: ${env:ENV}MapReduceMapper

functions:
  Driver:
    handler: handler.driver
  Mapper:
    handler: handler.mapper
    events:
      - sns:
          topicName: ${env:ENV}MapReduceMapper
          arn:
            Ref: SNSMapperTopic
  Reducer:
    handler: handler.reducer
    events:
      - s3:
          bucket: brianz-${env:ENV}-mapreduce-results
          event: s3:ObjectCreated:*
          rules:
            - suffix: '-done.csv'


plugins:
  - serverless-prune-plugin

custom:
  prune:
    automatic: true
    number: 2
